=== LuisRPAP/Lenguaje-de-Marcas/2evaluacion/Practica12.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libro (titulo,autores+,añoPublicacion,editorial,ISBN,fechaCompra)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre,apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT añoPublicacion (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT fechaCompra (dia,mes,año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ATTLIST libro recomendado (Sí|No) #REQUIRED>

=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica1-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM "Practica12.dtd">
<libro recomendado="No">  
  <titulo>Arde París</titulo>
  <autores>
      <autor>
          <nombre>Dominique</nombre>
          <apellido>Lapierre</apellido> 
      </autor>
      <autor>
          <nombre>Larry</nombre>
          <apellido>Collins</apellido> 
      </autor>
   </autores>
  <añoPublicacion>1975</añoPublicacion>
  <editorial>Alfaguara</editorial>
  <ISBN>97884010101</ISBN>
  <fechaCompra>
    <dia>12</dia>
    <mes>10</mes>
    <año>2012</año>
  </fechaCompra>
</libro>
