=== LuisRPAP/Lenguaje-de-Marcas/catalogo_plantas.dtd
<!ELEMENT CATALOGO (PLANTA*)>
<!ELEMENT PLANTA (IDENTIFICADOR,DATOS?)>
<!ELEMENT IDENTIFICADOR (#PCDATA)>
<!ELEMENT DATOS (ZONA,ILUMINACION*,PRECIO,CODIGO)  >
<!ELEMENT ZONA (#PCDATA)>
<!ELEMENT ILUMINACION (#PCDATA)>
<!ELEMENT PRECIO (#PCDATA)>
<!ELEMENT CODIGO (#PCDATA)>
<!ATTLIST IDENTIFICADOR IDIOMA (INGLÉS | ESPAÑOL) #REQUIRED>
<!ATTLIST DATOS GRUPO_BOTANICO CDATA #IMPLIED>

=== LuisRPAP/Lenguaje-de-Marcas/catalogo_plantas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="catalogo_plantas.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!-- <!DOCTYPE CATALOGO SYSTEM "catalogo_plantas.dtd"> -->
<CATALOGO>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="ESPAÑOL">Sanguinaria</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Sanguinaria canadensis">
			<ZONA>4</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>2.44</PRECIO>
			<CODIGO>031599</CODIGO>
		</DATOS>
	</PLANTA>
  <PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Phlox, Woodland</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Phlox divaricata">
			<ZONA>3</ZONA>
    		<ILUMINACION>sol</ILUMINACION>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>2.80</PRECIO>
			<CODIGO>012299</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Columbine</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Aquilegia canadensis">
			<ZONA>3</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>9.37</PRECIO>
			<CODIGO>030699</CODIGO>
    	</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="ESPAÑOL">Botón de oro</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Caltha palustris">
			<ZONA>4</ZONA>
			<ILUMINACION>mayormente soleado</ILUMINACION>
			<PRECIO>6.81</PRECIO>
			<CODIGO>051799</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Cowslip</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Caltha palustris">
			<ZONA>4</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>9.90</PRECIO>
			<CODIGO>030699</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Dutchman's-Breeches</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Dicentra cucullaria">
			<ZONA>3</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>6.44</PRECIO>
			<CODIGO>012099</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Ginger, Wild</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Asarum canadense">
			<ZONA>3</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>9.03</PRECIO>
			<CODIGO>041899</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Hepatica</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Hepatica americana">
			<ZONA>4</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>4.45</PRECIO>
			<CODIGO>012699</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Liverleaf</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Hepatica americana">
			<ZONA>4</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>3.99</PRECIO>
			<CODIGO>010299</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Jack-In-The-Pulpit</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Arisaema triphyllum">
			<ZONA>1</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>3.23</PRECIO>
			<CODIGO>020199</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Mayapple</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Podophyllum peltatum">
			<ZONA>3</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>2.98</PRECIO>
			<CODIGO>060599</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Phlox, Blue</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Phlox divaricata">
			<ZONA>3</ZONA>
    		<ILUMINACION>sol</ILUMINACION>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>5.59</PRECIO>
			<CODIGO>021699</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Spring-Beauty</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Claytonia Virginica">
			<ZONA>7</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>6.59</PRECIO>
			<CODIGO>020199</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Trillium</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Trillium grandiflorum">
			<ZONA>5</ZONA>
    		<ILUMINACION>sol</ILUMINACION>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>3.90</PRECIO>
			<CODIGO>042999</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Wake Robin</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Trillium grandiflorum">
			<ZONA>5</ZONA>
    		<ILUMINACION>sol</ILUMINACION>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>3.20</PRECIO>
			<CODIGO>022199</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Violet, Dog-Tooth</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Erythronium americanum">
			<ZONA>1</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>9.04</PRECIO>
			<CODIGO>020199</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Trout Lily</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Erythronium americanum">
			<ZONA>4</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>6.94</PRECIO>
			<CODIGO>032499</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Adder's-Tongue</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Erythronium americanum">
			<ZONA>4</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>9.58</PRECIO>
			<CODIGO>041399</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Anemone</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Anemone blanda">
			<ZONA>6</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>8.86</PRECIO>
			<CODIGO>122698</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Grecian Windflower</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Anemone blanda">
			<ZONA>6</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>9.16</PRECIO>
			<CODIGO>071099</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Bee Balm</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Monarda didyma">
			<ZONA>4</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>4.59</PRECIO>
			<CODIGO>050399</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Bergamot</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Monarda didyma">
			<ZONA>4</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>7.16</PRECIO>
			<CODIGO>042799</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Black-Eyed Susan</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Rudbeckia hirta">
			<ZONA>10</ZONA>
			<ILUMINACION>soleado</ILUMINACION>
			<PRECIO>9.80</PRECIO>
			<CODIGO>061899</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Buttercup</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Ranunculus">
			<ZONA>4</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>2.57</PRECIO>
			<CODIGO>061099</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Crowfoot</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Ranunculus">
			<ZONA>4</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>9.34</PRECIO>
			<CODIGO>040399</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="ESPAÑOL">Hierba de mariposa</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Asclepias tuberosa">
			<ZONA>10</ZONA>
			<ILUMINACION>soleado</ILUMINACION>
			<PRECIO>2.78</PRECIO>
			<CODIGO>063099</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Cinquefoil</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Potentilla">
			<ZONA>10</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>7.06</PRECIO>
			<CODIGO>052599</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Primrose</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Oenothera">
			<ZONA>2</ZONA>
			<ILUMINACION>soleado</ILUMINACION>
			<PRECIO>6.56</PRECIO>
			<CODIGO>013099</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Gentian</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Gentiana">
			<ZONA>4</ZONA>
    		<ILUMINACION>sol</ILUMINACION>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>7.81</PRECIO>
			<CODIGO>051899</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Blue Gentian</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Gentiana">
			<ZONA>4</ZONA>
			<ILUMINACION>sol</ILUMINACION>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>8.56</PRECIO>
			<CODIGO>050299</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Jacob's Ladder</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Polemonium caeruleum">
			<ZONA>10</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>9.26</PRECIO>
			<CODIGO>022199</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Greek Valerian</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Polemonium caeruleum">
			<ZONA>10</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>4.36</PRECIO>
			<CODIGO>071499</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">California Poppy</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Eschscholzia californica">
			<ZONA>10</ZONA>
			<ILUMINACION>sol</ILUMINACION>
			<PRECIO>7.89</PRECIO>
			<CODIGO>032799</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="ESPAÑOL">Estrella fugaz</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Dodecatheon">
			<ZONA>10</ZONA>
			<ILUMINACION>mayormente sombrío</ILUMINACION>
			<PRECIO>8.60</PRECIO>
			<CODIGO>051399</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="ESPAÑOL">Raíz de serpiente</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Cimicifuga">
			<ZONA>10</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>5.63</PRECIO>
			<CODIGO>071199</CODIGO>
		</DATOS>
	</PLANTA>
	<PLANTA>
		<IDENTIFICADOR IDIOMA="INGLÉS">Cardinal Flower</IDENTIFICADOR>
		<DATOS GRUPO_BOTANICO="Lobelia cardinalis">
			<ZONA>2</ZONA>
			<ILUMINACION>sombra</ILUMINACION>
			<PRECIO>3.02</PRECIO>
			<CODIGO>022299</CODIGO>
		</DATOS>
	</PLANTA>
</CATALOGO>
