=== LuisRPAP/Lenguaje-de-Marcas/Recuperacion2evaluacion_LRP/catalogo_cd.dtd
<!ELEMENT CATALOGO (CD*)>
<!ELEMENT CD (TITULO,ARTISTA*,PAIS,DISCOGRAFICA?,PRECIO*,AÑO,CODIGO?)>
<!ELEMENT TITULO (#PCDATA)>
<!ELEMENT ARTISTA (#PCDATA)  >
<!ELEMENT PAIS (#PCDATA)>
<!ELEMENT DISCOGRAFICA (#PCDATA)>
<!ELEMENT PRECIO (#PCDATA)>
<!ELEMENT AÑO (#PCDATA)>
<!ELEMENT CODIGO (#PCDATA)>
<!ATTLIST PRECIO MONEDA (DOLAR|LIBRA|EURO) #IMPLIED>

=== LuisRPAP/Lenguaje-de-Marcas/Recuperacion2evaluacion_LRP/catalogo_cd.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-model href="catalogo_cd.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!-- <!DOCTYPE CATALOGO SYSTEM "catalogo_cd.dtd"> -->

<CATALOGO>
	<CD>
		<TITULO>Empire Burlesque</TITULO>
		<ARTISTA>Bob Dylan</ARTISTA>
		<ARTISTA>Mari Trini</ARTISTA>
		<PAIS>USA</PAIS>
		<DISCOGRAFICA>Columbia</DISCOGRAFICA>
		<PRECIO MONEDA="DOLAR">10.90</PRECIO>
		<AÑO>1985</AÑO>
    	<CODIGO>531599</CODIGO>
	</CD>
	<CD>
		<TITULO>Hide your heart</TITULO>
		<ARTISTA>Bonnie Tyler</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>CBS Records</DISCOGRAFICA>
		<PRECIO MONEDA="DOLAR">9.90</PRECIO>
		<AÑO>1988</AÑO>
	</CD>
	<CD>
		<TITULO>Greatest Hits</TITULO>
		<ARTISTA>Dolly Parton</ARTISTA>
		<PAIS>USA</PAIS>
		<DISCOGRAFICA>RCA</DISCOGRAFICA>
		<PRECIO MONEDA="DOLAR">9.90</PRECIO>
		<AÑO>1982</AÑO>
	</CD>
	<CD>
		<TITULO>Still got the blues</TITULO>
		<ARTISTA>Gary Moore</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Virgin records</DISCOGRAFICA>
		<PRECIO MONEDA="LIBRA">10.20</PRECIO>
		<AÑO>1990</AÑO>
	</CD>
	<CD>
		<TITULO>Eros</TITULO>
		<ARTISTA>Eros Ramazzotti</ARTISTA>
		<PAIS>EU</PAIS>
		<DISCOGRAFICA>BMG</DISCOGRAFICA>
		<PRECIO MONEDA="EURO">9.90</PRECIO>
		<AÑO>1997</AÑO>
	</CD>
	<CD>
		<TITULO>One night only</TITULO>
		<ARTISTA>Bee Gees</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Polydor</DISCOGRAFICA>
		<PRECIO MONEDA="EURO">10.90</PRECIO>
		<AÑO>1998</AÑO>
	</CD>
	<CD>
		<TITULO>Sylvias Mother</TITULO>
		<ARTISTA>Dr.Hook</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>CBS</DISCOGRAFICA>
		<PRECIO MONEDA="DOLAR">8.10</PRECIO>
		<AÑO>1973</AÑO>
	</CD>
	<CD>
		<TITULO>Maggie May</TITULO>
		<ARTISTA>Rod Stewart</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Pickwick</DISCOGRAFICA>
		<PRECIO>8.50</PRECIO>
		<AÑO>1990</AÑO>
	</CD>
	<CD>
		<TITULO>Romanza</TITULO>
		<ARTISTA>Andrea Bocelli</ARTISTA>
		<PAIS>EU</PAIS>
		<DISCOGRAFICA>Polydor</DISCOGRAFICA>
		<PRECIO>10.80</PRECIO>
		<AÑO>1996</AÑO>
	</CD>
	<CD>
		<TITULO>When a man loves a woman</TITULO>
		<ARTISTA>Percy Sledge</ARTISTA>
		<PAIS>USA</PAIS>
		<DISCOGRAFICA>Atlantic</DISCOGRAFICA>
		<PRECIO>8.70</PRECIO>
		<AÑO>1987</AÑO>
	</CD>
	<CD>
		<TITULO>Black angel</TITULO>
		<ARTISTA>Savage Rose</ARTISTA>
		<PAIS>EU</PAIS>
		<DISCOGRAFICA>Elektra</DISCOGRAFICA>
		<PRECIO MONEDA="EURO">10.90</PRECIO>
		<AÑO>1995</AÑO>
		<CODIGO>031599</CODIGO>
	</CD>
	<CD>
		<TITULO>1999 Grammy Nominees</TITULO>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Grammy</DISCOGRAFICA>
		<PRECIO>8.20</PRECIO>
		<AÑO>1999</AÑO>
	</CD>
	<CD>
		<TITULO>For the good times</TITULO>
		<ARTISTA>Kenny Rogers</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Mucik Master</DISCOGRAFICA>
		<PRECIO MONEDA="EURO">8.70</PRECIO>
		<AÑO>1995</AÑO>
	</CD>
	<CD>
		<TITULO>Big Willie style</TITULO>
		<ARTISTA>Will Smith</ARTISTA>
		<PAIS>USA</PAIS>
		<DISCOGRAFICA>Columbia</DISCOGRAFICA>
		<PRECIO MONEDA="DOLAR">9.90</PRECIO>
		<AÑO>1997</AÑO>
		<CODIGO>123599</CODIGO>
	</CD>
	<CD>
		<TITULO>Tupelo Honey</TITULO>
		<ARTISTA>Van Morrison</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Polydor</DISCOGRAFICA>
		<PRECIO MONEDA="LIBRA">8.20</PRECIO>
		<AÑO>1971</AÑO>
	</CD>
	<CD>
		<TITULO>Soulsville</TITULO>
		<ARTISTA>Jorn Hoel</ARTISTA>
		<PAIS>Norway</PAIS>
		<DISCOGRAFICA>WEA</DISCOGRAFICA>
		<PRECIO>7.90</PRECIO>
		<AÑO>1996</AÑO>
		<CODIGO>345599</CODIGO>
	</CD>
	<CD>
		<TITULO>The very best of</TITULO>
		<ARTISTA>Cat Stevens</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Island</DISCOGRAFICA>
		<PRECIO>8.90</PRECIO>
		<AÑO>1990</AÑO>
	</CD>
	<CD>
		<TITULO>Stop</TITULO>
		<ARTISTA>Sam Brown</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>A and M</DISCOGRAFICA>
		<PRECIO>8.90</PRECIO>
		<AÑO>1988</AÑO>
	</CD>
	<CD>
		<TITULO>Bridge of Spies</TITULO>
		<ARTISTA>T'Pau</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Siren</DISCOGRAFICA>
		<PRECIO>7.90</PRECIO>
		<AÑO>1987</AÑO>
	</CD>
	<CD>
		<TITULO>Private Dancer</TITULO>
		<ARTISTA>Tina Turner</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>Capitol</DISCOGRAFICA>
		<PRECIO>8.90</PRECIO>
		<AÑO>1983</AÑO>
		<CODIGO>251599</CODIGO>
	</CD>
	<CD>
		<TITULO>Midt om natten</TITULO>
		<ARTISTA>Kim Larsen</ARTISTA>
		<PAIS>EU</PAIS>
		<DISCOGRAFICA>Medley</DISCOGRAFICA>
		<PRECIO MONEDA="EURO">7.80</PRECIO>
		<AÑO>1983</AÑO>
	</CD>
	<CD>
		<TITULO>Los tres Tenores</TITULO>
		<ARTISTA>Luciano Pavarotti</ARTISTA>
    	<ARTISTA>Plácido Domingo</ARTISTA>
    	<ARTISTA>José Carreras</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>DECCA</DISCOGRAFICA>
		<PRECIO>9.90</PRECIO>
		<AÑO>1991</AÑO>
	</CD>
	<CD>
		<TITULO>The dock of the bay</TITULO>
		<ARTISTA>Otis Redding</ARTISTA>
		<PAIS>USA</PAIS>
		<DISCOGRAFICA>Atlantic</DISCOGRAFICA>
		<AÑO>1987</AÑO>
		<CODIGO>789733</CODIGO>
	</CD>
	<CD>
		<TITULO>Picture book</TITULO>
		<ARTISTA>Simply Red</ARTISTA>
		<PAIS>EU</PAIS>
		<DISCOGRAFICA>Elektra</DISCOGRAFICA>
		<PRECIO MONEDA="EURO">7.20</PRECIO>
		<AÑO>1985</AÑO>
	</CD>
	<CD>
		<TITULO>Red</TITULO>
		<ARTISTA>The Communards</ARTISTA>
		<PAIS>UK</PAIS>
		<DISCOGRAFICA>London</DISCOGRAFICA>
		<PRECIO>7.80</PRECIO>
		<AÑO>1987</AÑO>
		<CODIGO>663600</CODIGO>
	</CD>
	<CD>
		<TITULO>Unchain my heart</TITULO>
		<ARTISTA>Joe Cocker</ARTISTA>
		<PAIS>USA</PAIS>
		<DISCOGRAFICA>EMI</DISCOGRAFICA>
		<PRECIO>8.20</PRECIO>
		<AÑO>1987</AÑO>
	</CD>
</CATALOGO>
