=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica 6/Practica62.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="Ncamas">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="3" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="THabitacion">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute name="Numero_de_camas" type="Ncamas" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="Ttitular">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Si" />
      <xs:enumeration value="No" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TNDoctor">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Cifuentes" />
      <xs:enumeration value="Casado" />
      <xs:enumeration value="Imaz" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Tdoctor">
    <xs:simpleContent>
      <xs:extension base="TNDoctor">
        <xs:attribute name="Titular" type="Ttitular" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:element name="hospital">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="paciente" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Nombre" type="xs:string" />
              <xs:element name="Habitacion" type="THabitacion" />
              <xs:element name="Doctor" type="Tdoctor" />
              <xs:element name="fechaNacimiento" type="xs:string" />
              <xs:element name="Varon" type="xs:boolean" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica 6/Practica62.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Practica62.xsd">
    <paciente>
        <Nombre>Jose Jimmenez Jemez</Nombre>
        <Habitacion Numero_de_camas="4">314</Habitacion>
        <Doctor Titular="Interino">Casado</Doctor>
        <fechaNacimiento>12 de enero de 2000</fechaNacimiento>
        <Varon>true</Varon>
    </paciente>
    <paciente>
        <Nombre>Felix Fernandez Flores</Nombre>
        <Habitacion Numero_de_camas=>201</Habitacion>
        <Doctor>Cifuentes</Doctor>
        <fechaNacimiento>13 de Febrero de 2001</fechaNacimiento>
        <Varon>true</Varon>
    </paciente>
    <paciente>
        <Nombre>Luisa Leris Lopez</Nombre>
        <Habitacion Numero_de_camas="2">222</Habitacion>
        <Doctor Titular="No">Imaz</Doctor>
        <fechaNacimiento>15 de abril de 2002</fechaNacimiento>
        <Varon>false</Varon>
    </paciente>
</hospital>
