=== LuisRPAP/Lenguaje-de-Marcas/XML/LUIS/Practica8/Practica8.1.dtd
<!ELEMENT concesionario (coche+)>

<!ELEMENT coche (
    marca,
    matricula,
    potencia,
    numPlazas,
    numPuertas,
    bajasEmisiones?
)>

<!ELEMENT marca (#PCDATA)>
<!ATTLIST marca
    modelo CDATA #REQUIRED
>

<!ELEMENT matricula (#PCDATA)>

<!ELEMENT potencia (#PCDATA)>
<!ATTLIST potencia
    combustible (gasolina | gasoil) #IMPLIED
>

<!ELEMENT numPlazas (#PCDATA)>
<!ELEMENT numPuertas (#PCDATA)>

<!ELEMENT bajasEmisiones EMPTY>
<!ATTLIST bajasEmisiones
    CO2 CDATA #IMPLIED
>

=== LuisRPAP/Lenguaje-de-Marcas/XML/LUIS/Practica8/Practica8.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "Practica8.1.dtd">

<concesionario>

    <coche>
        <marca modelo="León">SEAT</marca>
        <matricula>1234BBB</matricula>
        <potencia combustible="gasoil">130</potencia>
        <numPlazas>5</numPlazas>
        <numPuertas>5</numPuertas>
        <bajasEmisiones CO2="5"/> 
    </coche>
        
    <coche>
        <marca modelo="406">Peugeot</marca>
        <matricula>9067DYC</matricula>
        <potencia combustible="gasolina">90</potencia>
        <numPlazas>5</numPlazas>
        <numPuertas>4</numPuertas>
        <bajasEmisiones CO2=""/>
    </coche>

    <coche> 
        <marca modelo="serie 1">BMW</marca>
        <matricula>5678CCC</matricula>
        <potencia combustible="gasoil">150</potencia>
        <numPlazas>4</numPlazas>
        <numPuertas>3</numPuertas>
        <bajasEmisiones CO2=""/>
    </coche>

</concesionario>
