=== LuisRPAP/Lenguaje-de-Marcas/XML/LUIS/Practica7/Practica7.2.dtd
<!ELEMENT almacen (electrodomestico+)>

<!ELEMENT electrodomestico (
    referencia,
    tipo,
    marca,
    precioVenta,
    precioCoste?,
    color+,
    instalacion,
    localidad,
    año,
    unidades
)>

<!ELEMENT referencia (#PCDATA)>

<!ELEMENT tipo (#PCDATA)>
<!ATTLIST tipo
    eficiencia (A | B | C | D) #REQUIRED
>

<!ELEMENT marca (#PCDATA)>
<!ATTLIST marca
    modelo CDATA #IMPLIED
>

<!ELEMENT precioVenta (#PCDATA)>
<!ELEMENT precioCoste (#PCDATA)>

<!ELEMENT color (#PCDATA)>

<!ELEMENT instalacion (#PCDATA)>
<!ATTLIST instalacion
    accesorios (Panel | Puerta) #REQUIRED
>

<!ELEMENT localidad (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

=== LuisRPAP/Lenguaje-de-Marcas/XML/LUIS/Practica7/Practica7.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE almacen SYSTEM "Practica7.2.dtd">

<almacen>

    <electrodomestico>
        <referencia>A12345</referencia>
        <tipo eficiencia="A">Lavavajillas</tipo>
        <marca modelo="B23">Fagor</marca>
        <precioVenta>500</precioVenta>
        <precioCoste>395.50</precioCoste>
        <color>Blanco</color>
        <color>Negro</color>
        <instalacion accesorios="Puerta">Integrado</instalacion>
        <localidad>Logroño</localidad>
        <año>2013</año>
        <unidades>2</unidades>
    </electrodomestico>

    <electrodomestico>
        <referencia>HRJ345</referencia>
        <tipo eficiencia="A">Lavadora</tipo>
        <marca modelo="H111">Miele</marca>
        <precioVenta>400</precioVenta>
        <precioCoste>300</precioCoste>
        <color>Blanco</color>
        <instalacion accesorios="Puerta">Normal</instalacion>
        <localidad>Logroño</localidad>
        <año>2013</año>
        <unidades>0</unidades>
    </electrodomestico>

    <electrodomestico> 
        <referencia>B54321</referencia> 
        <tipo eficiencia="B">Frigorífico</tipo> 
        <marca modelo="NeoFrost">Siemens</marca> 
        <precioVenta>750</precioVenta> 
        <precioCoste>566.50</precioCoste> 
        <color>Metálico</color> 
        <instalacion accesorios="Panel">Integrado</instalacion> 
        <localidad>Arnedo</localidad> 
        <año>2013</año> 
        <unidades>1</unidades>
    </electrodomestico>

</almacen>
