=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica 7/Practica74.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="Nefi">
    <xs:restriction base="xs:string">
      <xs:enumeration value="A" />
      <xs:enumeration value="B" />
      <xs:enumeration value="C" />
      <xs:enumeration value="D" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Ttipo">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Eficiencia" type="Nefi" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="Tacc">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Panel" />
      <xs:enumeration value="Puerta" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Tins">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Accesorios" type="Tacc" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Tlinea">
    <xs:attribute name="linea" type="xs:integer" use="required" />
  </xs:complexType>

  <xs:simpleType name="Tref">
    <xs:restriction base="xs:string">
      <xs:length value="6" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Tloc">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Logroño" />
      <xs:enumeration value="Arnedo" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Tanio">
    <xs:restriction base="xs:string">
      <xs:length value="4" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Tuni">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>


  <xs:element name="Almacen">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Electrodomestico" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Referencia" type="Tref" />
              <xs:element name="Tipo" type="Ttipo" />
              <xs:element name="Marca">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Nombre" type="xs:string" />
                    <xs:element name="Pais" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="Modelo" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
              <xs:element name="Precio_de_venta" />
              <xs:element name="Precio_de_coste" minOccurs="0" />
              <xs:element name="Color" maxOccurs="unbounded" />
              <xs:choice>
                <xs:element name="Linea_blanca" type="Tlinea" />
                <xs:element name="Linea_marron" type="Tlinea" />
              </xs:choice>
              <xs:element name="Instalacion" type="Tins" />
              <xs:element name="Localidad" type="Tloc" />
              <xs:element name="Anio" type="Tanio" />
              <xs:element name="Unidades" type="Tuni" />

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica 7/Practica74.xml
<?xml version="1.0" encoding="UTF-8"?>
<Almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Practica74.xsd">
    <Electrodomestico>
        <Referencia>A1234</Referencia>
        <Tipo Eficiencia="A">Lavavajillas</Tipo>
        <Marca Modelo="B23">
            <Nombre>Fagor</Nombre>
            <Pais>España</Pais>
        </Marca>
        <Precio_de_venta>500</Precio_de_venta>
        <Precio_de_coste>395.50</Precio_de_coste>
        <Color>Blanco</Color>
        <Color>Negro</Color>
        <Linea_blanca linea="5" />
        <Instalacion Accesorios="Puerta">Integrado</Instalacion>
        <Localidad>Logroño</Localidad>
        <Anio>2013</Anio>
        <Unidades>2</Unidades>
    </Electrodomestico>
    <Electrodomestico>
        <Referencia>HRH345</Referencia>
        <Tipo Eficiencia="A">Lavadora</Tipo>
        <Marca Modelo="H111">
            <Nombre>Miele</Nombre>
            <Pais>Alemania</Pais>
        </Marca>
        <Precio_de_venta>400</Precio_de_venta>
        <Precio_de_coste>300</Precio_de_coste>
        <Color>Blanco</Color>
        <Linea_blanca linea="2" />
        <Instalacion Accesorios="Puerta">Normal</Instalacion>
        <Localidad>Zaragoza</Localidad>
        <Anio>13</Anio>
        <Unidades>-5</Unidades>
    </Electrodomestico>
    <Electrodomestico>
        <Referencia>B54321</Referencia>
        <Tipo Eficiencia="B">Frigorifico</Tipo>
        <Marca Modelo="NeoFrost">
            <Nombre>Siemens</Nombre>
            <Pais>Alemania</Pais>
        </Marca>
        <Precio_de_venta>750</Precio_de_venta>
        <Precio_de_coste>566.50</Precio_de_coste>
        <Color>Metalico</Color>
        <Linea_blanca linea="1" />
        <Instalacion Accesorios="Panel">Integrado</Instalacion>
        <Localidad>Arnedo</Localidad>
        <Anio>2013</Anio>
        <Unidades>1</Unidades>
    </Electrodomestico>
    <Electrodomestico>
        <Referencia>ABC123</Referencia>
        <Tipo Eficiencia="B">Horno</Tipo>
        <Marca Modelo="H23">
            <Nombre>Balay</Nombre>
            <Pais>España</Pais>
        </Marca>
        <Precio_de_venta>200</Precio_de_venta>
        <Precio_de_coste>125.50</Precio_de_coste>
        <Color>Negro</Color>
        <Linea_marron linea="7" />
        <Instalacion Accesorios="Puerta">Normal</Instalacion>
        <Localidad>Logroño</Localidad>
        <Anio>2013</Anio>
        <Unidades>5</Unidades>
    </Electrodomestico>
</Almacen>
