=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica 7/Practica73.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="Nefi">
    <xs:restriction base="xs:string">
      <xs:enumeration value="A" />
      <xs:enumeration value="B" />
      <xs:enumeration value="C" />
      <xs:enumeration value="D" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Ttipo">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Eficiencia" type="Nefi" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Tmarca">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Modelo" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="Tacc">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Panel" />
      <xs:enumeration value="Puerta" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Tins">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Accesorios" type="Tacc" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:element name="Almacen">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Electrodomestico" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Referencia" />
              <xs:element name="Tipo" type="Ttipo" />
              <xs:element name="Marca" type="Tmarca" />
              <xs:element name="Precio_de_venta" />
              <xs:element name="Precio_de_coste" />
              <xs:element name="Color" maxOccurs="unbounded" />
              <xs:element name="Instalacion" type="Tins" />
              <xs:element name="Localidad" />
              <xs:element name="Año" />
              <xs:element name="Unidades" />

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LuisRPAP/Lenguaje-de-Marcas/XML/Practica 7/Practica73.xml
<?xml version="1.0" encoding="UTF-8"?>
<Almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Practica73.xsd">
    <Electrodomestico>
        <Referencia>A12345</Referencia>
        <Tipo Eficiencia="A">Lavabajillas</Tipo>
        <Marca Modelo="B23">Fagor</Marca>
        <Precio_de_venta>500</Precio_de_venta>
        <Precio_de_coste>395.50</Precio_de_coste>
        <Color>Blanco</Color>
        <Color>Negro</Color>
        <Instalacion Accesorios="Puerta">Integrado</Instalacion>
        <Localidad>Logroño</Localidad>
        <Año>2013</Año>
        <Unidades>2</Unidades>
    </Electrodomestico>
</Almacen>
